# Generated by Django 4.0.6 on 2022-07-22 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_video_file_alter_video_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 17, 14, 32, 802077)),
        ),
    ]
