# Generated by Django 4.0.6 on 2022-07-22 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_video_duration_video_size_alter_video_upload_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 17, 31, 5, 132465)),
        ),
    ]
